package sc.pirate.app.tempo

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Conformance tests for [PurchaseContentCrypto].
 *
 * The expected privateScalarHex / publicKeyHex values are the canonical reference
 * vectors generated by the Web implementation (apps/web/tests/content-crypto.test.ts).
 * All platforms (Web, Android, Desktop) MUST produce identical values for the same
 * rootSeed + purchaseId inputs.
 */
class PurchaseContentCryptoTest {

    private fun hexToBytes(hex: String): ByteArray {
        val h = hex.removePrefix("0x")
        return ByteArray(h.length / 2) { i ->
            h.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
    }

    private fun bytesToHex(bytes: ByteArray): String =
        bytes.joinToString("") { "%02x".format(it.toInt() and 0xFF) }

    private fun aesGcmEncrypt(key: ByteArray, iv: ByteArray, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, SecretKeySpec(key, "AES"), GCMParameterSpec(128, iv))
        return cipher.doFinal(plaintext)
    }

    @Test
    fun derivePurchaseKeyPair_matchesCanonicalVectors() {
        data class Vector(
            val rootSeedHex: String,
            val purchaseId: String,
            val expectedPrivateScalarHex: String,
            val expectedPublicKeyHex: String,
        )

        val vectors = listOf(
            Vector(
                rootSeedHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
                purchaseId = "purchase-001",
                expectedPrivateScalarHex = "0x0b318d9a7318a006f9a8616e76f09807cc41c68a4315663a4bee268ab5721a45",
                expectedPublicKeyHex = "0x046d6123e1d10ec91ecd980bfe1cf5cb9d6fd883cc274bec1fe15d75bfc76d4d21702ef9206c6b866ea65f40a447377b636cf7f8a63d81468178d7b7926124b114",
            ),
            Vector(
                rootSeedHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
                purchaseId = "purchase-xyz",
                expectedPrivateScalarHex = "0x8a91df0f2a77438986461140f82b7117f1faa03939848d8245712b83078d6fe7",
                expectedPublicKeyHex = "0x04843ae04927ab280d4e0357a32808c3f027ae95a13046c583378aa035963ad83ef8f0edb693086adf136b0abd7448382549a5e1c5f7486d3d3aaf638144b841a0",
            ),
            Vector(
                rootSeedHex = "8f2a6c1e5b7790d4e8a1f3c5b7d9e0f112233445566778899aabbccddeeff001",
                purchaseId = "purchase-001",
                expectedPrivateScalarHex = "0x5b474d21dca22b47215d31e6b9c14e6dd4a2731cb2b49d79574111ffeeb3ffed",
                expectedPublicKeyHex = "0x04b34af1e4ca93c09930bd8cd9e273e6324a0d57c60f06cbfecee343ac13842c2270d14b8522193aba3c19d0e142801d28582a1fda7060850e53fa98a3dc85b81e",
            ),
            Vector(
                rootSeedHex = "8f2a6c1e5b7790d4e8a1f3c5b7d9e0f112233445566778899aabbccddeeff001",
                purchaseId = "purchase-xyz",
                expectedPrivateScalarHex = "0xbb7dd7c8df822c36d5dcf191026f0c4c290e279704300a3fdd2eae8d001b5781",
                expectedPublicKeyHex = "0x04610a59c5b04c29109fc07af8851bd50ac4dd14ae944abc0192c2d7718d3aaa1ef42458c052098b6dad27d26cdefb7c0d6e3dddb8742282bc862ef1818bdfd77d",
            ),
        )

        for (v in vectors) {
            val rootSeed = hexToBytes(v.rootSeedHex)
            val pair = PurchaseContentCrypto.derivePurchaseKeyPair(rootSeed, v.purchaseId)

            val actualPrivHex = "0x" + bytesToHex(pair.privateScalarBytes)
            val actualPubHex = "0x" + bytesToHex(pair.publicKeyBytes)

            assertEquals(
                "privateScalarHex mismatch for purchaseId=${v.purchaseId}",
                v.expectedPrivateScalarHex,
                actualPrivHex,
            )
            assertEquals(
                "publicKeyHex mismatch for purchaseId=${v.purchaseId}",
                v.expectedPublicKeyHex,
                actualPubHex,
            )
        }
    }

    @Test
    fun derivePurchaseSeed_changesWith_purchaseId() {
        val rootSeed = ByteArray(32) { it.toByte() }
        val seedA = PurchaseContentCrypto.derivePurchaseSeed(rootSeed, "purchase-001")
        val seedB = PurchaseContentCrypto.derivePurchaseSeed(rootSeed, "purchase-002")
        assertNotEquals(bytesToHex(seedA), bytesToHex(seedB))
    }

    @Test
    fun derivePurchaseSeed_changesWith_rootSeed() {
        val rootSeedA = ByteArray(32) { it.toByte() }
        val rootSeedB = ByteArray(32) { (it + 1).toByte() }
        val seedA = PurchaseContentCrypto.derivePurchaseSeed(rootSeedA, "purchase-001")
        val seedB = PurchaseContentCrypto.derivePurchaseSeed(rootSeedB, "purchase-001")
        assertNotEquals(bytesToHex(seedA), bytesToHex(seedB))
    }

    @Test
    fun unwrapAndDecrypt_roundTripWorks() {
        val rootSeed = hexToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        val pair = PurchaseContentCrypto.derivePurchaseKeyPair(rootSeed, "purchase-001")

        val dek = ByteArray(32) { i -> ((i * 7) and 0xFF).toByte() }
        val wrapped = EciesContentCrypto.eciesEncrypt(pair.publicKeyBytes, dek)
        val envelope = PurchaseContentCrypto.PurchaseEnvelope(
            ephemeralPub = wrapped.ephemeralPub,
            iv = wrapped.iv,
            ciphertext = wrapped.ciphertext,
        )

        val unwrappedDek = PurchaseContentCrypto.unwrapDekFromEnvelope(pair.privateScalarBytes, envelope)
        assertArrayEquals(dek, unwrappedDek)

        val plaintext = "pirate-android-content-crypto-smoke".toByteArray(Charsets.UTF_8)
        val artifactIv = ByteArray(12) { i -> i.toByte() }
        val artifactCiphertext = aesGcmEncrypt(unwrappedDek, artifactIv, plaintext)
        val ivPrependedArtifact = artifactIv + artifactCiphertext

        val decrypted = PurchaseContentCrypto.decryptIvPrependedArtifact(unwrappedDek, ivPrependedArtifact, 12)
        assertArrayEquals(plaintext, decrypted)
    }
}
